workflows:
  ios-workflow:
    name: iOS Build (Simulator)
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          pod install --project-directory=ios
      - name: Build iOS for simulator
        script: flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
